apiVersion: v1
data:
    password: ENC[AES256_GCM,data:R5Jl9viVThk=,iv:ERMH+gsyEXBhjFTGB3r6caZrJAl70vw40iFBLPKFM8E=,tag:r+ln+qKVIkUryBwLA41l+g==,type:str]
    user: ENC[AES256_GCM,data:z/mwy9tydlA=,iv:nAd+vug96j2oftdLWfs6fbm1hWf/OzjS99712yaFf5k=,tag:3ZuLOs86dYmllioURJJB+A==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMTZaOXdyL01EeFltOHpZ
            YWZWZjdGcm8wbDltM1FpQlQ0ZWthN0FxaFIwCkxJalpieXpyTzFlVjFYTW9QZVcv
            ZHdETG9zQWw1UktnakVHcjhHZFVLVkEKLS0tIE9BNWovcW1iMjYrWFRqS3FTV3ZG
            UUptZm5HLzE1NHdFeDc2UEpEa0JJRjQK11CAbVZh7j3H7RXTKEcYkqqSjWfKqI7w
            xbEsiN9HvbNP0EFeXPRTtRf7r9kKVorXWIkjtgC3lDvlhA3fgSNmpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v042xwen427mha33g7jzwfxnld5yg2ehfk8zjumzttd69494cecq6wa5zx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T14:57:52Z"
    mac: ENC[AES256_GCM,data:V8kJrhLNp8hviG9jnhrTSO8vwERTirXlJD66WiAxgQUg7BLv1u9lFl2YuJxfC8Xs5xkgxeP5AyVt7qjuHBVQVU7C6kurzj+ukWGEIgHtxRBxuWcsnbeg8NZt/hIFgsPQpWubTID4/VXoIq7f1b5n8zItn5qjuc+zYXeM2ZIREOA=,iv:x/TAUf9LbwqdyxDHeDO3lfvkuX4P9OZLPEHy32WtcC8=,tag:TznI13k19nsMd7UoPm3DMA==,type:str]
    version: 3.13.1
