apiVersion: v1
data:
    password: ENC[AES256_GCM,data:8xxW/5nFvzg=,iv:sPi7IkgsnSbvFmZjC+D9Ub36OsYcsUPg8NAhlz+nC0o=,tag:ggOl9tnZ9HUNRAi3FVUr1Q==,type:str]
    user: ENC[AES256_GCM,data:43VmTq/7+ME=,iv:Tz+boBJmz0WLaUgck+aGTmk78YE+rzeWUdmlIcSaBSs=,tag:6/GVIL7+woxAXZPK1KbWBw==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQXFxUmsyQWczTUNYSHcz
            MXVNUjdFNmRPMmRNcEpyVzNnVEZvMXU1VUFnCm0vYnpodDJOa0gwZFdVQk1QeDJo
            YWQ0blcrd2FKbkM4ampscGpyOXRKeGcKLS0tIGg2aldCSlh4ZVM3eUNVeHQyZXAr
            eEV3c2RzaWVibjRIRGROR3hlVjZYVkEKwQbRwpjUUteSbsfZd3vaU9Rpmn/llOMC
            c4wTuLRDvs9QLM0SxcfoRSo7Zgn4JyjIxwRacdfKkEFQlukYNUcfsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ldvxfzu09xuc0epsmwllp2r8t9l9h9xh5c8psmtpcr2qpa97ayjq7n2qze
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T15:07:58Z"
    mac: ENC[AES256_GCM,data:YbdATE01Vh9OovP4x3/zUcN0lupMX31AjtHf2VtITGe4ecX64cjkSc/fRj1WEht+XmOZJCr1YIXwZNH6iQyblwHHwqpgpg42hEMJo7+vL+9X7hlZ1ZeycpohUzryWoERxOOd1JZo0aXQrGpJ/6lqxy+2DiyGF+YSmaPYrllOYIQ=,iv:D5CKFCejAdxnNdBoFIHVeUNXMgComMnhpP4mi25DzV4=,tag:DdWo8iBPheMxYq6Q3CvuvA==,type:str]
    version: 3.13.1
