apiVersion: v1
data:
    TunnelSecret: ENC[AES256_GCM,data:kOMT9jue4IsHgWas7OChbZVTdreGNoSsWJsvPVPjSYpwnUaurmXr1cuAklmCq58BAT+vLnA7euDFXmrA,iv:fbn/9j2tQ//W5Ax75PzF9jvz3SnmrV4h0KXC5kZFjFU=,tag:UI3fjt8f/dycyVRPpaEGZg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNDJ0U3FLUXlpVE9nTWc1
            cVZyNURtMWZpMUhPRDJwN3FJY2RIWS8wR1djCm5xTkZNWGFRNUZYT0oydmdBVWd6
            SjJVb0tmSGEvSkRsQnBucUZTSmtKMjAKLS0tIFdsa1dBbzhJSGYvSTFKODJUQTN1
            MkpFMGJ0UnV5VThsTXVtN3JaWitGY2cKot2pdVf5XV7eUGtD9WXUa5eA8VMw/V4z
            rs43lzE7iADPI/WGglsUg9PbwtQqVyvoJIGt1BzSuEdpkRPDnm3eaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v042xwen427mha33g7jzwfxnld5yg2ehfk8zjumzttd69494cecq6wa5zx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T16:30:40Z"
    mac: ENC[AES256_GCM,data:toNKMz/idzl/gC4ixO9NddqbqzuSRG+4focBISqNdHegJzPbkg4VUbXGmYAyqUZw8qOOY3sZP3O1d8JO7mTOGr/LlQ5zvC59rtNWidTnVtDniXhzU0jHzSYAxzGqOKGJB2SWqYSCSNjP8srYsQROQ8cc9azTn/SzaSWEMi9HpoA=,iv:lrz7gDOcFfQnjbxTSWVwF42yUpERTidgTeNoaMZy4kU=,tag:0NovE+aZKSG6HPn0Tw0SOg==,type:str]
    version: 3.13.1
