apiVersion: v1
data:
  d314fdbc-9bb4-4dfd-96bb-2236e32a3dff.json: eyJBY2NvdW50VGFnIjoiMjNmNWQyZjcyMTEzNDAwN2UwZmFiZWVkMjgwOTk0MjQiLCJUdW5uZWxTZWNyZXQiOiJVYUxuVEVOK3c2ZXkzS0wzUzJUSFZoN3cxT1p5ZmswQitiaHVKZzlIbEZzPSIsIlR1bm5lbElEIjoiZDMxNGZkYmMtOWJiNC00ZGZkLTk2YmItMjIzNmUzMmEzZGZmIiwiRW5kcG9pbnQiOiIifQ==
kind: Secret
metadata:
  name: tunnel-credentials
