apiVersion: v1
data:
    d314fdbc-9bb4-4dfd-96bb-2236e32a3dff.json: ENC[AES256_GCM,data:4xGRBIYmBPtH+14VYVeKP+42qS6QQq74o1zVqUa5qgdDYzze3pVbj8yH1zHM9VPzi//3rZfZPyrATbyt//iiZhdrAzwMdM4EF4yp/diyAslfc5j1lqagYxT7Dw8bjvL+EEkaLCqY5PQIddNUZvXxqLqnqnM+sEGBgIqefCHWCyp0J0MEsRSQtYf/hvW7JpkzSIQ8h/WqFFb52tkkEeKvdj2sW3oTL7Wypy2wbProkH/2DlEU6z0ZRQw9I5Qi5JyxtMb2zyEm58uI3jsMfT+Nlc3eoDNfXAuTQ5EwLcjmCFxrADdKXp8u15awf1s=,iv:v09ZV3a1jev1iRL7H+z7dj27JVAIvdcvF68LBHrpFdU=,tag:XMN4F4jeCS61/89ERfkwMA==,type:str]
kind: Secret
metadata:
    name: test-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SFFHY2F1UFR0OHpTV1J3
            bnR5OTJEUVlrdlg1TUFhMU9vSVlkTDg4WEVBCjQzSTcrdHByQ0NITGg0QU1NSCtM
            dUdJdEdkRFE3dExSd1JGbUJqUSsxRlkKLS0tIDNUdjVuWnIyRGxyUUpSR3d4MjEv
            QkhvL29EalgxdDE5bzVxT2JhbGozUmMKKNnXaU7Xycw+irzZi8IE50pmDq49Gv3L
            rSKWn7CF54ctDNpbt/5kPf/sUsg6+HJkp3HYpLdPgnZx3vDkSK4rKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v042xwen427mha33g7jzwfxnld5yg2ehfk8zjumzttd69494cecq6wa5zx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T17:37:12Z"
    mac: ENC[AES256_GCM,data:qPPx124UAa0yyYqOwhu0vj8ew4gpuke2GJIcKuq8IOR2QCjj/L1vtbJ5didEdu8HvMaEpCZOlcrVhxqPP7h9c9IjXl+iLP3PGRsqak7LcJNGdPgVxQ1zz772+o1s/qjAYZFAv+hvC+ph4lAvY+8t4XTp3ZO2YmDJBYxlKc50Pbs=,iv:8wnI1m3nJ2W2bjwqTvl3xprlvPpNbuiY0PDfElRvwtw=,tag:K9DasCyvAa6j4idZ7HCk7w==,type:str]
    version: 3.13.1
